steps:
  - label: ":hammer: Example Script"
    command: |
      WEBHOOK="$(buildkite-agent meta-data get buildkite:webhook)"
      ISSUE_TITLE="$(jq .head_commit.message <<< ${WEBHOOK})"
      echo $ISSUE_TITLE

